#!/bin/bash
set -x

if [[ $CR_MC_J2K_HOME = "" ]]; then
	echo "Error. CR_MC_J2K_HOME is not defined"
	exit 1
fi

if [ ! -d $CR_MC_J2K_HOME/MCJ2K/bin ]; then
    mkdir $CR_MC_J2K_HOME/MCJ2K/bin
fi

make -C src