MAKEFILE = Makefile

all:
	cd ../tools; make -f $(MAKEFILE) all	
	cd ../knapsack; make -f $(MAKEFILE) all	
	cd ../knapsack/j2c_to_knapsack_files; make -f $(MAKEFILE) all 
	cd ../src/CR; make -f $(MAKEFILE) all 
	#cd ../MCJ2K/src; make -f $(MAKEFILE) all 

clean:
	cd ../tools; make -f $(MAKEFILE) clean
	cd ../knapsack; make -f $(MAKEFILE) clean	
	cd ../knapsack/j2c_to_knapsack_files; make -f $(MAKEFILE) clean 
	cd ../src/CR; make -f $(MAKEFILE) clean 	
	#cd ../MCJ2K/src; make -f $(MAKEFILE) clean 